### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by acutesoftware** [msakuta/farmsim#1]
Hello,
  I had a play with the farming simulator and it looks like a good baseline to build a nice game.

Can you let us know what the license is (MIT, GPL?)

I am looking to integrate some short simple games to host on a website that keeps scores and player states, so any changes I make I'd send back pull requests.

Thanks

**Comment by msakuta** [comment]
I hadn't think this simulator had reusable value since it's so experimental, so I didn't feel the need to supply a license. But if you want to use it, I'm okay with the most liberal license as possible. Probably MIT license?

Also, if you intend to fork this repository, be aware that there are two main branches. The master branch depends on an external library, pixi.js, which is hardware-accelerated graphics library, but it's not suitable for a rather static game such as farmsim. So I branched no-pixi, which is an attempt to get rid of dependency of pixi.js. It turned out that simple HTML elements such as div and img worked quite well for such a game (and they are more mobile-friendly), so now I consider the master branch obsolete. 
However, there are remnants of pixi.js dependencies which I haven't bother cleaning up, even in no-pixi branch.

Also, I am not satisfied with the simulation model. It doesn't have seasons, temperature, extreme weather, terrain, wild animals and such kind of things you would worry about if you are into gardening. That said, making the simulation too detailed and accurate doesn't always make playing with it fun. It is a difficult decision of game design, but I think a full-fledged game requires careful consideration on it.

**Comment by acutesoftware** [comment]
Thanks for the information!
